# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run unit tests
      - name: Run tests
        run: ./gradlew test --parallel

  internal-testing-release:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Build bundle
      - name: Build bundle
        run: ./gradlew :app:bundlePRODRelease

      # Create service_acount.json file
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      # Upload to PlayStore for Internal Testing
      - name: Deplay to PlayStore (Internal Testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: gr.cpaleop.teithe_apps
          releaseFile: app/build/output/bundle/pRODRelease/app-pROD-release.aab
          track: internal
          userFraction: 1.0
          whatsNewDirectory: distribution/whatsnew/
          mappingFile: app/build/outputs/mapping/pRODRelease/mapping.txt
